# Generated by Django 5.1.1 on 2024-10-16 16:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2024, 10, 16, 16, 43, 11, 239677, tzinfo=datetime.timezone.utc))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authdemo.user')),
            ],
        ),
    ]
