# Generated by Django 5.1.1 on 2024-12-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authdemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
