# Generated by Django 5.1.1 on 2024-10-17 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authdemo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='session',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 13, 28, 14, 806321, tzinfo=datetime.timezone.utc)),
        ),
    ]
