# Generated by Django 5.1.1 on 2024-10-17 14:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authdemo', '0002_rename_user_id_session_user_alter_session_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 14, 11, 12, 718165, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authdemo.user'),
        ),
    ]
