# Generated by Django 5.1.1 on 2024-10-19 18:55

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authdemo', '0003_alter_session_expiry_alter_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='expiry',
            field=models.DateTimeField(default=datetime.timedelta(seconds=300)),
        ),
    ]
