# Generated by Django 5.1.1 on 2024-10-20 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authdemo', '0004_session_created_at_alter_session_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiry',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
