# Generated by Django 5.1.1 on 2024-11-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authdemo', '0006_alter_session_expiry_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='container',
            field=models.JSONField(default=dict),
        ),
    ]
