# Generated by Django 5.1.1 on 2024-11-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authdemo', '0008_fileupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='FileUploadTracker',
        ),
    ]
